name: Generate GitHub ASCII Artwork
on:
  push
jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Install Figlet Program
      run: sudo apt-get install figlet -y

    - name: Create GitHub Actions Banner
      run: figlet "GitHub Actions" > github_actions.txt

    - name: Verify Output File Is Not Empty
      run: test -s github_actions.txt

    - name: Read Banner File
      run: cat github_actions.txt

    - name: List Repo Files
      run: ls -ltra
