name: Store and Share ASCII Banner

on:
  push:

jobs:
  generate_banner:
    runs-on: ubuntu-latest
    steps:
      - name: Install figlet
        run: sudo apt-get install figlet -y

      - name: Generate ASCII Banner
        run: figlet
